---
abstract: 'Get subroutine arguments from command line arguments (@ARGV)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Data::Clone: 0
  Test::More: 0.98
  blib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-GetArgs-Argv
requires:
  Data::Sah: 0.02
  JSON: 0
  Log::Any: 0
  Perinci::Sub::GetArgs::Array: 0.09
  Perinci::Sub::Util: 0
  Rinci: v1.1.10
  YAML::Syck: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Perinci-Sub-GetArgs-Argv/
  repository: http://github.com/sharyanto/perl-Perinci-Sub-GetArgs-Argv
version: 0.24
