---
abstract: 'Get subroutine arguments from command line arguments (@ARGV)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Data::Clone: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-GetArgs-Argv
requires:
  Data::Clean::FromJSON: 0.11
  Data::Sah: 0.02
  JSON: 0
  Log::Any: 0
  Perinci::Sub::GetArgs::Array: 0.09
  Perinci::Sub::Util: 0
  Rinci: v1.1.40
  YAML::Syck: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Perinci-Sub-GetArgs-Argv
  homepage: https://metacpan.org/release/Perinci-Sub-GetArgs-Argv
  repository: git://github.com/sharyanto/perl-Perinci-Sub-GetArgs-Argv.git
version: 0.28
